CREATE USER AdminBL IDENTIFIED BY "biblioteca123";

GRANT CONNECT, RESOURCE TO AdminBL;

GRANT CREATE SESSION TO AdminBL;
GRANT CREATE TABLE TO AdminBL;
GRANT CREATE ANY TABLE TO AdminBL;
GRANT DROP ANY TABLE TO AdminBL;
GRANT SELECT ANY TABLE TO AdminBL;
GRANT INSERT ANY TABLE TO AdminBL;
GRANT UPDATE ANY TABLE TO AdminBL;
GRANT DELETE ANY TABLE TO AdminBL;

GRANT CREATE PROCEDURE TO AdminBL;
GRANT ALTER ANY PROCEDURE TO AdminBL;
GRANT DROP ANY PROCEDURE TO AdminBL;
GRANT EXECUTE ANY PROCEDURE TO AdminBL;

GRANT CREATE TRIGGER TO AdminBL;
GRANT ALTER ANY TRIGGER TO AdminBL;
GRANT DROP ANY TRIGGER TO AdminBL;

-- Asignar cuota ilimitada
ALTER USER AdminBL QUOTA UNLIMITED ON USERS;

-- Eliminar usuario
-- DROP USER AdminBL CASCADE;